name: store_cashier
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  shimmer: 3.0.0
  firebase_core: 2.24.2
  firebase_analytics: 10.8.0
  firebase_remote_config: 4.3.8
  google_fonts: 6.1.0
  package_info_plus: 4.2.0
  get_storage: 2.1.1
  intl: 0.18.0
  pretty_http_logger: 1.0.3
  logger: 2.0.2+1
  font_awesome_flutter: 10.6.0
  uuid: 4.2.2
  modal_bottom_sheet: ^3.0.0-pre
  flutter_easyloading: 3.0.5
  image: 4.1.4
  image_picker: 1.0.7
  flutter_image_utilities: 2.1.0
  syncfusion_flutter_pdfviewer: 24.1.45
  flutter_pdfview: 1.3.2
  file_picker: 6.1.1
  dotted_border: 2.1.0
  flutter_svg: 2.0.9
  camera: 0.10.5+9
  flutter_portal: 1.1.4
  connectivity_plus: 5.0.2
  google_sign_in: 6.1.6
  sign_in_with_apple: 5.0.0
  firebase_auth: 4.16.0
  crypto: 3.0.3
  cloud_firestore: 4.14.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: 0.13.1
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/svg/
    - assets/icons/
  uses-material-design: true

