// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZtDPyTPxu4yn7GdM7429mS5RPmXePVt0',
    appId: '1:651649985274:web:3aa498f28986dd50e57743',
    messagingSenderId: '651649985274',
    projectId: 'store-cashier-dev',
    authDomain: 'store-cashier-dev.firebaseapp.com',
    storageBucket: 'store-cashier-dev.appspot.com',
    measurementId: 'G-9W6BBVEH23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6uS8QBftehMp_IOorszj-wMEN2AMUhuo',
    appId: '1:651649985274:android:cfb4c27d0b645d66e57743',
    messagingSenderId: '651649985274',
    projectId: 'store-cashier-dev',
    storageBucket: 'store-cashier-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn_YbhTPIHxO3r5Jmg8LVAVYNJHpl_Dm0',
    appId: '1:651649985274:ios:f1dbedc877af00f1e57743',
    messagingSenderId: '651649985274',
    projectId: 'store-cashier-dev',
    storageBucket: 'store-cashier-dev.appspot.com',
    iosBundleId: 'com.freddydev.storeCashier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn_YbhTPIHxO3r5Jmg8LVAVYNJHpl_Dm0',
    appId: '1:651649985274:ios:c0b34b0dbd86c3aae57743',
    messagingSenderId: '651649985274',
    projectId: 'store-cashier-dev',
    storageBucket: 'store-cashier-dev.appspot.com',
    iosBundleId: 'com.freddydev.storeCashier.RunnerTests',
  );
}
